# Generated by Django 5.1.6 on 2025-05-05 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
